// Concatenates src/scripts/bridge-lib/*.jsx (in dependency order) + bridge-entry.jsx
// into src/scripts/MCP Bridge.jsx — the single flat file AE actually loads/deploys.
// See bridge-entry.jsx's header comment for why this is build-time concatenation
// rather than an ExtendScript #include.
import * as fs from "fs";
import * as path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const scriptsDir = path.join(__dirname, "..", "src", "scripts");
const libDir = path.join(scriptsDir, "bridge-lib");

const LIB_ORDER = [
  "json-polyfill.jsx",
  "utils.jsx",
  "project-info.jsx",
  "layers.jsx",
  "keyframes-expressions.jsx",
  "effects.jsx",
  "viewport.jsx",
  "jsx-runner.jsx",
  "command-io.jsx"
];

const header = `// MCP Bridge.jsx — GENERATED by scripts/build-bridge.js, do not edit directly.\n// Edit src/scripts/bridge-lib/*.jsx (command handlers) or src/scripts/bridge-entry.jsx\n// (UI/polling), then \`npm run build\` regenerates this file.\n\n`;

const parts = [header];
for (const file of LIB_ORDER) {
  parts.push(`// ---- bridge-lib/${file} ----\n`);
  parts.push(fs.readFileSync(path.join(libDir, file), "utf8"));
  parts.push("\n");
}
parts.push(`// ---- bridge-entry.jsx ----\n`);
parts.push(fs.readFileSync(path.join(scriptsDir, "bridge-entry.jsx"), "utf8"));

fs.writeFileSync(path.join(scriptsDir, "MCP Bridge.jsx"), parts.join(""));
console.log("Generated src/scripts/MCP Bridge.jsx");
